# Generated by Django 4.1.13 on 2024-08-06 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "person_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "last_contacted",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date of last contact"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Surname"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Company"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Position"
                    ),
                ),
                (
                    "company_adress",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Company's adress",
                    ),
                ),
                (
                    "lead_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Not_processed", "Not_processed"),
                            ("In_progress", "In_progress"),
                            ("Processed", "Processed"),
                            ("Closed", "Closed"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Lead Status",
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Internet Search", "Internet Search"),
                            ("Social Media", "Social Media"),
                            ("Blogs", "Blogs"),
                            ("Private Reccomendation", "Private Reccomendation"),
                            ("Podcasts", "Podcasts"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Lead Source",
                    ),
                ),
                (
                    "exact_source",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Exact Source",
                    ),
                ),
                (
                    "form_filling_page",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Form filling page",
                    ),
                ),
                (
                    "total_visit_time",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Total site visit time",
                    ),
                ),
                (
                    "contact_purpose",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "IT_Infrastructure_Optimization",
                                "IT Infrastructure Optimization",
                            ),
                            ("Information_Security", "Information Security"),
                            ("Project_Management", "Project Management"),
                            (
                                "Web_Application_Development",
                                "Web Application Development",
                            ),
                            (
                                "Business_Process_Automation",
                                "Business Process Automation",
                            ),
                            ("Marketing", "Marketing"),
                            ("Finance Analysis", "Finance Analysis"),
                            ("Data_Analysis", "Data Analysis"),
                            ("AI_Implementation", "AI Implementation"),
                            ("Efficiency_Improvement", "Efficiency Improvement"),
                            ("Post_Project_Support", "Post-Project Support"),
                            ("Business_Consulting", "Business Consulting"),
                            ("Mobile_App_Development", "Mobile App Development"),
                            ("CRM_Implementation", "CRM Implementation"),
                            ("API_Implementation", "API Implementation"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Lead Source",
                    ),
                ),
                (
                    "full_problem",
                    models.CharField(
                        blank=True,
                        max_length=1025,
                        null=True,
                        verbose_name="Full problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
            },
        ),
    ]
