version: '3.8' 
  
services:
  django:
    build:
      context: .
    volumes:
      - "./website:/website"
    # env_file:
    #   - "ArtemSheptalin/.env"
    depends_on:
      - mongo
  
  mongo:
    image: mongo:6.0.3
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db/
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGODB_NAME=production_database
      - MONGODB_USER=manager
      - MONGODB_PASSWORD=123qwe
  
  nginx:
    image: nginx:latest
    container_name: nginx_django
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./website/staticfiles/admin:/etc/nginx/website/website/staticfiles/admin"
    ports:
      - "8080:8080"
    depends_on:
      - django

volumes:
  mongodb_data:


